### ISSUE TITLE
They might have changed the html structure again, getting errors when trying to download.

### ISSUE THREAD

**Issue by ecibus** [OtchereDev/coursehunter-video-downloader#12]

**Comment by OtchereDev** [comment]
It was changed recently, so i made a push last friday that solved it. Make a git pull to get the updated changes to the code

**Comment by gonewild22** [comment]
Nope, it must have been changed this night again.
[Errno 36] File name too long: .... player.add Event Listener(play,on Play);player.add Event Listener(subtitle,function(e){if(e&&e.info&&e.info==='off'){local Storage.set Item('subtitle'.mp4""....Report issue github repo (sry I've opened a new issue accidentally)

**Comment by OtchereDev** [comment]
Don't worry... I am on it... I will make push very soon to correct it... So watch the repo

**Comment by OtchereDev** [comment]
The issue has been solved...Make a git pull and enjoy 🥂
