### ISSUE TITLE
Broken again

### ISSUE THREAD

**Issue by gonewild22** [OtchereDev/coursehunter-video-downloader#13]
Nope, it must have been changed this night again.
[Errno 36] File name too long: .... player.add Event Listener(play,on Play);player.add Event Listener(subtitle,function(e){if(e&&e.info&&e.info==='off'){local Storage.set Item('subtitle'.mp4""....Report issue github repo

**Comment by OtchereDev** [comment]
Don't worry... I am on it... I will make push very soon to correct it... So watch the repo

**Comment by gonewild22** [comment]
Thank you so much! I really appreciate your great work!

**Comment by OtchereDev** [comment]
The issue has been solved...Make a git pull and enjoy...Dont forget to leave a ⭐ too
