### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by RangerCoder99** [OtchereDev/coursehunter-video-downloader#18]
Seems they made changes to the site, I keep getting:

`Incorrect log-in details...Retry with correct log-in details

Or it might be the URL link to the course site

 if not any of the above, report to GitHub repo`

But the login details and URL were correct I checked two times to make sure

**Comment by OtchereDev** [comment]
Sorry.... I think it broken beyond pair because I can't seem to find a way to get it to work. I am building a new web crawler, so then hope it able to do the same job

**Comment by RangerCoder99** [comment]
oh no! wonder if this is helpful seems that the new player got one small settings wheel and one download option, to get the video... not sure if it's possible to script that in... new web crawler sounds interesting!

**Comment by OtchereDev** [comment]
@RangerCoder99 https://github.com/OtchereDev/coursehunter_downloader 

The new downloader is ready... Please try it out and let me know if it working on your end.
