### ISSUE TITLE
Error while downloading

### ISSUE THREAD

**Issue by saadazghour** [OtchereDev/coursehunter-video-downloader#2]
![error](https://user-images.githubusercontent.com/33766249/92460809-5167e680-f1c0-11ea-8293-62f0037e7293.PNG)

### Tested both and not working :  

- **(eg. https://coursehunter.net/course_name)** **&&**   **(eg. https://coursehunter.net/course/course_name)**

![errrrrrr](https://user-images.githubusercontent.com/33766249/92460814-52991380-f1c0-11ea-8419-73aca17d58f4.PNG)

**Comment by OtchereDev** [comment]
hello Azghour-Saad, sorry for the inconvience, the script was returning the wrong javascript function but it has been solved. Thank you

**Comment by OtchereDev** [comment]
This is it....Working now @Azghour-Saad 
![github_issue](https://user-images.githubusercontent.com/59093261/92574068-250ea180-f276-11ea-953e-2b3f9cee68ff.PNG)
