### ISSUE TITLE
Downloaded videos *updating* if they got the same name

### ISSUE THREAD

**Issue by RangerCoder99** [OtchereDev/coursehunter-video-downloader#4]
Some issues with courses that use the same video names multiple times, like it doesn't include the number in the video name.
 It happened with:

/course/next-js-polnyy-kurs
and  /course/next-js-s-react-i-node-krasivoe-prilozhenie-portfolio

In the last one, it keeps overwriting *updating* any video that has the name: ProjectOverview.mp4
And in the first, it goes totally crazy and only downloads some videos of the course not sure what's going on there.

**Comment by OtchereDev** [comment]
@RangerCoder99 sorry for that, was it after the latest commit please, because I have gotten such an issue yet?

**Comment by RangerCoder99** [comment]
Think it was an issue before the latest commit, not sure if its a windows thing because it also removes all the spaces from the video file names.

**Comment by OtchereDev** [comment]
> Think it was a issue before, not sure of its a windows think because it also strips all the spaces from the video file namesOn Sep 14, 2020 11:53 PM, OtchereDev <notifications@github.com> wrote: @RangerCoder99 sorry for that, was it after the latest commit please, because I have gotten such an issue yet? —You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or unsubscribe.

I did not get what you meant, if you would clearer a bit it will be helpful. And if you can add an image I will appreciate it. For what I know of, a video updates if and only if it is not fully downloaded, I.e when the size of the copy on your computer is not equal to the one coming from coursehunter. Does your video download completely please?

**Comment by OtchereDev** [comment]
@RangerCoder99 and you the name space stripping is not from the code, that is how coursehunter.net stored it in their code. So sorry nothing can done about it.

**Comment by RangerCoder99** [comment]
Sorry edited that last comment, it´s late. I´m trying to reproduce the errors. And no worries about the space stripping!

**Comment by OtchereDev** [comment]
@RangerCoder99  Can you please check if the course folder that it has a video with the name `.mp4` just that??, I think i am having similar problem now

**Comment by RangerCoder99** [comment]
I think the issue seems to be a problem with the characters in the names. None of the files got numbers here and the one overwriting only got the ¨-MasteringNext.js.mp4¨ part of the name? It´s strange. 
See what happened in the log in the images below...

(this was a test of /course/next-js-polnyy-kurs) the folder name is next-js-polnyy-kurs 

![error-1](https://user-images.githubusercontent.com/22674459/93167224-8ad7af00-f6f6-11ea-9bad-e52c130380e7.png)
![error-2](https://user-images.githubusercontent.com/22674459/93167225-8ca17280-f6f6-11ea-90c7-2b4144e5b07a.png)
[video.txt](https://github.com/OtchereDev/coursehunter-video-downloader/files/5222545/video.txt)

**Comment by OtchereDev** [comment]
@RangerCoder99 okaaaayy nice, I have solved the issue but I will make the commit in some hours time. When it is push here please use the Range option to continue your download, so that that you don't duplicate stuff. Thank you.

**Comment by OtchereDev** [comment]
@RangerCoder99  Please don't forget to comment here if the new commit is working as expected, if it is committed.

**Comment by OtchereDev** [comment]
@RangerCoder99 hello the commit has been made try it out and let me know if it working ......you will notice that i have include the spaces in the title.... :)

**Comment by RangerCoder99** [comment]
Awesome testing it now...

**Comment by RangerCoder99** [comment]
Yes it's working great and the spaces look good, you made it even better! (while spaces can use some improvements but its much better now!)
![error](https://user-images.githubusercontent.com/22674459/93227758-1bd87580-f74b-11ea-9d0b-1e743a371ba1.png)

**Comment by OtchereDev** [comment]
Nice👍🏽
