### ISSUE TITLE
Create a download pop up in pysimplegui 

### ISSUE THREAD

**Issue by OtchereDev** [OtchereDev/coursehunter-video-downloader#6]
Create a pop up in pysimplegui that has the following features:
- A title which is the current downloading video 
- file: which is file name of the current course video being downloaded 
- folder : which folder is video being downloaded to
- downloaded : that show the percentage of the file that has being downloaded 

A sample sketch :
 
![IMG_20201007_100112](https://user-images.githubusercontent.com/59093261/95318025-7d40bf80-0885-11eb-94d2-04078dac9bee.jpg)

A typical example:
![IMG_20201007_081334](https://user-images.githubusercontent.com/59093261/95318194-b842f300-0885-11eb-8266-564bb18fee34.png)

**Comment by polo123qwe** [comment]
I would like to give this a go

**Comment by OtchereDev** [comment]
Please go ahead
