### ISSUE TITLE
without this code some of windows users cant run the main.py

### ISSUE THREAD

**Issue by mbaah80** [OtchereDev/coursehunter-video-downloader#8]
pip install --upgrade Werkzeug==0.16.0

**Comment by OtchereDev** [comment]
Yes please, but this problem has solved in a close issue already where I provide three solutions to the werkzeung problem. But do you have any suggestions that it might be solved permanently

**Comment by mbaah80** [comment]
just include the werkzeug in your readme so that it will prompt those who face the problem.

**Comment by OtchereDev** [comment]
Alright I will work that.... Hope it the downloader is working right for you??
